CREATE DATABASE "colors"
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;


create table if not exists colors(
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name varchar not null,
	year varchar not null,
	color varchar not null,
	pantone_value varchar not null
)